spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/brainoverflow
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true

jwt:
  secret: 823e399822c5170927c9802b3feb60b1fe54debefb406ca5f4eaf05e0014ea63
  expiration-ms: 6000000
