version: "3.8"

# 공통 설정을 앵커로 분리
x-spring-common: &spring-common
  build:
    context: .
    dockerfile: Dockerfile
  image: my-spring-app:latest
  depends_on:
#    - postgres
    - redis
#    - rabbitmq
  environment:
    PROFILE: dev
    # PostgreSQL
    SPRING_DATASOURCE_URL:      jdbc:postgresql://host.docker.internal:5432/brainoverflow
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: postgres
    # Redis
    REDIS_HOST: redis
    REDIS_PORT: 6379
    # RabbitMQ
    SPRING_RABBITMQ_HOST:       host.docker.internal
    SPRING_RABBITMQ_PORT:       5672

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # RabbitMQ (with management UI)
#  rabbitmq:
#    image: rabbitmq:4.0-management
#    container_name: rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#      - "61613:61613"   # <-- STOMP TCP 포트 추가
#  # STOMP 플러그인 활성화를 위해 커맨드를 오버라이드
#    command: >
#      bash -lc "rabbitmq-plugins enable --offline rabbitmq_stomp rabbitmq_web_stomp &&
#               rabbitmq-server"
  # Spring Boot 애플리케이션 3개 인스턴스

  spring-1:
    <<: *spring-common
    ports:
      - "8080:8080"

  spring-2:
    <<: *spring-common
    ports:
      - "8081:8080"

  spring-3:
    <<: *spring-common
    ports:
      - "8082:8080"
#
#volumes:
#  postgres_data:
