---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: brain-overflow
  namespace: brain-overflow
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`brain-overflow.unknownpgr.com`)
      kind: Rule
      services:
        - name: brain-overflow-nginx
          port: 80
  tls:
    secretName: brain-overflow-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-overflow-nginx
  namespace: brain-overflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-overflow-nginx
  template:
    metadata:
      labels:
        app: brain-overflow-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: brain-overflow-nginx
  namespace: brain-overflow
spec:
  selector:
    app: brain-overflow-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
